### ISSUE TITLE
Coverage is making source map locations invalid

### ISSUE THREAD

**Issue by jason0x43** [theintern/istanbul-loader#4]
Without the coverage loader:

```
× node - EventProxy - #getElementTextPath (0.002s)
    AssertionError: expected 'BODY[1][normalize-space(string())="Hello, world"]' to equal '/HTML/BODY[1][normalize-space(string())="Hello, world"]'
      at Test.#getElementTextPath [as test]  <webpack:/tests/unit/EventProxy.ts:202:11>
      at <src/lib/Test.ts:260:47>
```

With the coverage loader:

```
× node - EventProxy - #getElementTextPath (0.002s)
    AssertionError: expected 'BODY[1][normalize-space(string())="Hello, world"]' to equal '/HTML/BODY[1][normalize-space(string())="Hello, world"]'
      at Test.#getElementTextPath [as test]  <webpack:/tests/unit/EventProxy.ts:1:32180>
      at <src/lib/Test.ts:260:47>
```

Note the source locations in `tests/unit/EventProxy.ts`.

**Comment by jason0x43** [comment]
Note that the case above is somewhat invalid because the the test code itself was being instrumented, which shouldn't typically be done. However, the base problem of instrumentation breaking source locations still exists.
